# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
  - bash: |
      git checkout develop &&
      git config --global user.email "system@pinnakl.com" &&
      git config --global user.name "Tarun Kapoor" &&
      npm version patch -m "%s [skip azurepipelines]" &&

    displayName: 'Copy to Github'
