import { ReportOptions } from '@pnkl-frontend/shared';

export class ManagerReportsReportOptions {
  carry: ReportOptions;
  positionsWithMv: ReportOptions;
  riskAnalytics: ReportOptions;
  tradesReportAggregate: ReportOptions;

  constructor() {
    // tslint:disable:max-line-length
    const positionsWithMvReportOptions =
      '{"id":5,"parameters":{"posdate":"20180103"},"reportingColumns":[{"include":false,"filters":["CMST"],"name":"AccountCode","reportingColumnType":"report","type":"text","viewOrder": -1},{"include":true,"name":"Analyst","reportingColumnType":"report","type":"text"},{"include":true,"name":"AssetType","reportingColumnType":"report","type":"text"},{"include":true,"name":"Description","reportingColumnType":"report","type":"text"},{"include":true,"name":"FolderCode","reportingColumnType":"report","type":"text"},{"include":true,"name":"Identifier","reportingColumnType":"report","type":"text"},{"include":true,"name":"LocalCurrency","reportingColumnType":"report","type":"text"},{"include":true,"name":"MVUSD","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"MVUSDPct","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Position","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"PriceLocal","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Sector","reportingColumnType":"report","type":"text"},{"include":true,"name":"Strategy","reportingColumnType":"report","type":"text"},{"include":true,"name":"Ticker","reportingColumnType":"report","type":"text"},{"include":true,"name":"Trader","reportingColumnType":"report","type":"text"}]}';
    const tradesReportAggregateReportOptions =
      '{"id":2,"parameters":{"startdate":"20171201","enddate":"20180131"},"reportingColumns":[{"include":false,"filters":["CMST"],"name":"Account","reportingColumnType":"report","type":"text","viewOrder": -1},{"include":true,"name":"Accrued","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"AssetType","reportingColumnType":"report","type":"text"},{"include":true,"name":"Broker","reportingColumnType":"report","type":"text"},{"include":true,"name":"Commission","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Currency","reportingColumnType":"report","type":"text"},{"include":true,"name":"description","reportingColumnType":"report","type":"text"},{"include":true,"name":"Fee","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Folder","reportingColumnType":"report","type":"text"},{"include":true,"name":"Identifier","reportingColumnType":"report","type":"text"},{"include":true,"name":"NetMoneyLocal","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"PB","reportingColumnType":"report","type":"text"},{"include":true,"name":"Price","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Quantity","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"SettleDt","reportingColumnType":"report","type":"date"},{"include":true,"name":"Strategy","reportingColumnType":"report","type":"text"},{"include":true,"name":"TRS","reportingColumnType":"report","type":"text"},{"include":true,"name":"Ticker","reportingColumnType":"report","type":"text"},{"include":true,"name":"TradeDt","reportingColumnType":"report","type":"date"},{"include":true,"name":"TrType","reportingColumnType":"report","type":"text"}]}';
    const riskAnalyticsReportOptions =
      '{"id":11,"parameters":{"posdate":"20180103"},"reportingColumns":[{"include":true,"name":"AssetType","reportingColumnType":"report","type":"text"},{"include":true,"name":"AvgLife","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Convexity","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"CurrentYield","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Cusip","reportingColumnType":"report","type":"text"},{"include":true,"name":"DV01","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Description","reportingColumnType":"report","type":"text"},{"include":true,"name":"Duration_Modified","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Ticker","reportingColumnType":"report","type":"text"},{"include":true,"name":"YTM","reportingColumnType":"report","type":"numeric"}]}';
    const carryReportOptions =
      '{"id":24,"parameters":{"positiondate":"20180103"},"reportingColumns":[{"include":false,"filters":["CMST"],"name":"AccountCode","reportingColumnType":"report","type":"text","viewOrder": -1},{"include":true,"name":"Ann_Cpn","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Ann_Cpn_Pct","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Ann_Div","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Ann_Div_Pct","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"AssetType","reportingColumnType":"report","type":"text"},{"include":true,"name":"Coupon","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Cusip","reportingColumnType":"report","type":"text"},{"include":true,"name":"Description","reportingColumnType":"report","type":"text"},{"include":true,"name":"Dividend","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Identifier","reportingColumnType":"report","type":"text"},{"include":true,"name":"MVUSD","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Position","reportingColumnType":"report","type":"numeric"},{"include":true,"name":"Ticker","reportingColumnType":"report","type":"text"}]}';
    // tslint:enable:max-line-length

    this.carry = JSON.parse(carryReportOptions);
    this.positionsWithMv = JSON.parse(positionsWithMvReportOptions);
    this.riskAnalytics = JSON.parse(riskAnalyticsReportOptions);
    this.tradesReportAggregate = JSON.parse(tradesReportAggregateReportOptions);
  }
}
