export class SecurityFromApi {
  constructor(
    public assettype: string,
    public assettypeid: string,
    public countryofincorporation: string,
    public countryofrisk: string,
    public currency: string,
    public currencyid: string,
    public cusip: string,
    public datasource: string,
    public description: string,
    public id: string,
    public isin: string,
    public loanid: string,
    public manualpricingindicator: string,
    public moodyrating: string,
    public multiplier: string,
    public opracode: string,
    public organization_id: string,
    public organizationname: string,
    public organization_status_descr: string,
    public organization_status_id: string,
    public organizationticker: string,
    public privateindicator: string,
    public sandprating: string,
    public sector: string,
    public sectype: string,
    public sectypedescription: string,
    public sectypeid: string,
    public sedol: string,
    public ticker: string,
    public principal_factor: string,
    public initialmargin: string,
    public maintenancemargin: string,
    public maturity: string,
    public underlyingsecid: string = null
  ) {}
}
